import datetime

x = datetime.datetime.now()
print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%b"))
print(x.strftime("%B"))
print(x.strftime("%c"))
print(x.strftime("%d"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%j"))
print(x.strftime("%m"))
print(x.strftime("%M"))
print(x.strftime("%p"))